---
title: "Collaborative Research Project - Assignment 3"
bibliography:
date: "24 October 2014"
output: pdf_document
number_sections: yes
highlight: zenburn
authors: Meilin Moellenkamp and Nicolas Rosemberg
toc: yes
---

```{r, echo=FALSE, include=FALSE}

### 1. Setting Working Directory & Loading the data
# error=FALSE
# Setting the Working Directory
setwd("/Users/Meilin/Desktop/Collaborative Social Data/Research-Project-Assignment-3")
# setwd("/Users/Nico/Documents/Hertie/Social science data analysis/CollaborativeResearchProject")

# Loading the merged file from the Working directory
Merged <- read.csv(file="MergedData")
```

```{r, echo=FALSE, include=FALSE}
### 2. Load Required Packages

# install.packages("RJOSONIO")  
library(RJSONIO)
# install.packages("WDI")  
library(WDI)
# install.packages("dplyr")  
library(dplyr) 
# install.packages("tidyr")  
library(tidyr)
# install.packages("httr")  
library(httr) 
# install.packages("dplyr")  
library(dplyr)
# install.packages("XML")  
library(XML)
#install.packages("plyr")
library(plyr)
# install.packages("Amelia")  
library(Amelia) 
#install.packages("XLConnect")
library(XLConnect)    
# install.packages("countrycode")
library("countrycode")
# install.packages ("ggplot2")
library(ggplot2)
# # install.packages ("magrittr")
library(magrittr)
# install.packages ("fmsb")
library(fmsb)
# install.packages ("car")
library(car)
# install.packages("stargazer")
library(stargazer)


### 3. Check if Variables are coded as numeric
str(Merged)
# Code variables as numeric
Merged$Incidence <- as.numeric(Merged$Incidence)
Merged$DPT <- as.numeric(Merged$DPT)
Merged$Measles <- as.numeric(Merged$Measles)

```

